spring.application.name=moneytransfer-service

# ========== Active Profile ==========
spring.profiles.active=uat

# ========== Server ==========
server.port=8080
server.servlet.context-path=/api/v1

# ========== Actuator ==========
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ========== Logging ==========
logging.config=classpath:logback-spring.xml
