# ========== UAT Profile ==========

# ========== MS SQL Server DataSource ==========
spring.datasource.url=jdbc:sqlserver://sqlserver:1433;databaseName=demodb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=${DB_SA_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ========== JPA / Hibernate ==========
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.data.redis.host=redis
spring.data.redis.port=6379

ibm.mq.queueManager=${MQ_QMGR_NAME}
ibm.mq.channel=DEV.APP.SVRCONN
ibm.mq.connName=mq(1414)
ibm.mq.user=${MQ_APP_USER}
ibm.mq.password=${MQ_APP_PASSWORD}

# ========== Logging ==========
logging.level.root=INFO
logging.level.th.co.muangthai=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=INFO
